name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancement des tests
      run: |
        python -m pytest test-unitaire.py

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSHPRIVATEKEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} "whoami"
      env:
        SSHPRIVATEKEY: ${{ secrets.SSHPRIVATEKEY }}


    

