name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancement des tests
      run: |
        python -m pytest test-unitaire.py

    - name: Test connexion with our Azure VM
      run: |
        ssh -i ${{ secrets.SSHPRIVATEKEY }} devopsadmin@172.205.208.129  echo "SSH successful"

      

